export const REQUEST_LIST = 'IDEAS_REQUEST_LIST';
export const REQUEST_LIST_SUCCEEDED = 'IDEAS_REQUEST_LIST_SUCCEEDED';
export const REQUEST_LIST_FAILED = 'IDEAS_REQUEST_LIST_FAILED';

export const REQUEST_SINGLE = 'IDEAS_REQUEST_SINGLE';
export const REQUEST_SINGLE_SUCCEEDED = 'IDEAS_REQUEST_SINGLE_SUCCEEDED';
export const REQUEST_SINGLE_FAILED = 'IDEAS_REQUEST_SINGLE_FAILED';
